language: php
php:
    - '7.0'
    #- hhvm
    #- nightly

services:
    - mysql

before_script:
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - composer install
    - php bin/console doctrine:database:create --env=travis
    - php bin/console doctrine:schema:create --env=travis
    #- php bin/console doctrine:fixtures:load -n --env=travis

script:
    - phpunit

notifications:
    email:
        - resurtm+travis-ci@gmail.com
