parameters:

services:
    app.listener.email_queue_pusher:
        class: AppBundle\EventListener\EmailQueuePusher
        arguments: ['@leezy.pheanstalk', '@serializer']
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.command.email_worker_command:
        class: AppBundle\Command\Worker\EmailWorkerCommand
        arguments: ['@leezy.pheanstalk', '@serializer', '@app.service.email_sender']
        tags:
            - { name: console.command }

    app.service.email_sender:
        class: AppBundle\Service\EmailSender
        arguments: ['@mailer', '@templating', "%email_support%", "%email_from%"]
