# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    email_queue_pusher:
        class: AppBundle\EventListener\EmailQueuePusher
        arguments: ['@leezy.pheanstalk', '@serializer']
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.command.email_worker_command:
        class: AppBundle\Command\Worker\EmailWorkerCommand
        arguments: ['@leezy.pheanstalk', '@serializer']
        tags:
            - { name: console.command }
